baseURL = "http://www.apachecon.com/acasia2021"
languageCode = "en-us"
title = "ApacheCon Asia 2021"
theme = "apachecon"
# When enabled, creates URL of the form /filename.html instead of /filename/.
uglyURLs = true
buildFuture = true
