# set the baseURL for CI verification
baseURL = "/"
title = "ApacheCon Asia 2023"
theme = "apachecon"
# When enabled, creates URL of the form /filename.html instead of /filename/.
uglyURLs = true
#hasCJKLanguage = true
enableRobotsTXT = true

languageCode = "en-us"
DefaultContentLanguage = "en"



[params]
  author = "ALC-Beijing"
  description = "Welcome to CommunityOverCode (ApacheCon Asia) 2023"
  keywords = ["CommunityOverCode","CommunityOverCodeAsia","ApacheConAsia2023"]
  schedule = ["2023-08-18", "2023-08-19", "2023-08-20"]

[languages.en]
languageName = "English"
weight = 1

[languages.zh]
languageName = "中文"
weight = 2

disableKinds = ["taxonomy", "taxonomyTerm"]

[markup.goldmark.renderer]
unsafe = true

# menu for en ((final list includes translated pages from /content)
[[languages.en.menu.main]]
name = "Schedule"
url = "/tracks.html"
weight = -100

# menu for ZH language (final list includes translated pages from /content)

[[languages.zh.menu.main]]
name = "会议日程"
url = "/zh/tracks.html"
weight = -100

 
